import {
  Skeleton,
  SkeletonCircle,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
} from "@chakra-ui/react";
import {Box, Flex, Grid, GridItem} from "@chakra-ui/layout";

const DashboardSkeleton = ({children}) => {
  return (
    <>
      <Flex alignItems="center" justifyContent="center" bg="white" minW="100vw">
        <Flex
          direction="row"
          justifyContent="space-between"
          alignItems="center"
          w="100%"
          maxW="1250px"
          p={5}
        >
          <Flex direction="row" alignItems="center">
            <SkeletonCircle size="10" mr={4} />
            <Skeleton
              display={["none", "initial"]}
              rounded={16}
              minH="10px"
              maxH="10px"
              minW="40px"
              maxW="40px"
              mr={4}
            />
            <Skeleton
              display={["none", "initial"]}
              rounded={16}
              minH="10px"
              maxH="10px"
              minW="40px"
              maxW="40px"
              mr={4}
            />
            <Skeleton
              display={["none", "initial"]}
              rounded={16}
              minH="10px"
              maxH="10px"
              minW="40px"
              maxW="40px"
            />
          </Flex>
          <Flex alignItems="center">
            <Skeleton
              rounded={8}
              minH="40px"
              maxH="40px"
              minW="40px"
              maxW="40px"
            />
          </Flex>
        </Flex>
      </Flex>
      <Flex
        maxW="1250px"
        direction="column"
        justifyContent="center"
        position="relative"
        mx="auto"
      >
        <Flex
          alignSelf="center"
          minW="30%"
          minH="20%"
          position="absolute"
          alignItems="center"
          justifyContent="center"
          bg="brand.100"
          zIndex="1"
          rounded={8}
        >
          {children}
        </Flex>
        <Grid gap={5} m={5} justifyItems={["center", "initial"]}>
          <GridItem
            rowStart={[1]}
            rowSpan={[1]}
            colStart={[1]}
            colSpan={[1]}
            maxW="100%"
          >
            <Flex
              minW={["90vw", "100%"]}
              minH="100%"
              direction={["column", "row"]}
              bg="white"
              rounded={16}
              p={5}
            >
              <Flex
                minW={["100%", "50%"]}
                maxW={["100%", "50%"]}
                minH={["50%", "100%"]}
                maxH={["50%", "100%"]}
                direction="column"
                justifyContent="center"
                mr={[0, 4]}
                mb={[4, 0]}
              >
                <Flex direction="row" alignItems="center" mb={4}>
                  <SkeletonCircle size="10" mr={4} />
                  <Skeleton rounded={16} minH="20px" minW="60%" />
                </Flex>
                <Skeleton minH="40px" minW="100%" rounded={16} mb={4} />
                <Skeleton minH="40px" minW="100%" rounded={16} />
              </Flex>
              <Box
                minW={["100%", "50%"]}
                maxW={["100%", "50%"]}
                minH={["50%", "100%"]}
                maxH={["50%", "100%"]}
              >
                <Table minW="100%" minH="100%">
                  <Thead>
                    <Tr>
                      <Th>
                        <Skeleton
                          minH="15px"
                          rounded={16}
                          minW="20px"
                          maxW="60%"
                        />
                      </Th>
                      <Th>
                        <Skeleton
                          minH="15px"
                          rounded={16}
                          minW="20px"
                          maxW="60%"
                        />
                      </Th>
                      <Th>
                        <Skeleton
                          minH="15px"
                          rounded={16}
                          minW="20px"
                          maxW="60%"
                        />
                      </Th>
                    </Tr>
                  </Thead>
                  <Tbody>
                    <Tr>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                    </Tr>
                    <Tr>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                    </Tr>
                    <Tr>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                      <Td>
                        <Skeleton
                          minH="10px"
                          rounded={16}
                          minW="20px"
                          maxW="50%"
                        />
                      </Td>
                    </Tr>
                  </Tbody>
                </Table>
              </Box>
            </Flex>
          </GridItem>
          <GridItem
            rowStart={[2]}
            rowSpan={[1]}
            colStart={[1]}
            colSpan={[1]}
            maxW="100%"
          >
            <Flex
              minW={["90vw", "100%"]}
              minH="100%"
              bg="white"
              rounded={16}
              px={5}
              pt={5}
              alignItems="flex-end"
              justifyContent="space-between"
            >
              <Skeleton minH="70px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="100px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="130px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="160px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="190px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="150px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="110px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="90px" minW="5%" maxW="10%" mr={[2, 5]} />
              <Skeleton minH="70px" minW="5%" maxW="10%" />
            </Flex>
          </GridItem>
          <GridItem
            rowStart={[3, 1]}
            rowSpan={[1, 2]}
            colStart={[1, 2]}
            colSpan={[1]}
            maxW="100%"
          >
            <Flex
              minW={["90vw", "100%"]}
              minH="100%"
              bg="white"
              rounded={16}
              p={5}
            >
              <Table minW="100%" minH="100%">
                <Thead>
                  <Tr>
                    <Th>
                      <Skeleton
                        minH="15px"
                        rounded={16}
                        minW="20px"
                        maxW="60%"
                      />
                    </Th>
                    <Th>
                      <Skeleton
                        minH="15px"
                        rounded={16}
                        minW="20px"
                        maxW="60%"
                      />
                    </Th>
                    <Th>
                      <Skeleton
                        minH="15px"
                        rounded={16}
                        minW="20px"
                        maxW="60%"
                      />
                    </Th>
                  </Tr>
                </Thead>
                <Tbody>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                  <Tr>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                    <Td>
                      <Skeleton
                        minH="10px"
                        rounded={16}
                        minW="20px"
                        maxW="50%"
                      />
                    </Td>
                  </Tr>
                </Tbody>
              </Table>
            </Flex>
          </GridItem>
        </Grid>
      </Flex>
    </>
  );
};

export default DashboardSkeleton;
